version: "3.8"

services:
  php:
    build:
      context: .
    container_name: hermes_backend
    volumes:
      - ./:/var/www/html
    networks:
      - hermes_backend
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
    networks:
      - hermes_backend
  
  db:
    image: mariadb:10.7.4
    container_name: hermes_db
    env_file:
      - ./docker/.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - hermes_backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hermes_pma
    env_file:
      - ./docker/.env
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER-hermes}
      PMA_PASSWORD: ${MYSQL_PASSWORD-JfEUTDaRPxm5}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - hermes_backend
  
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  hermes_backend:
